version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  reviewers:
  - kotarella1110
  versioning-strategy: increase
  ignore:
  - dependency-name: webpack
    versions:
    - ">= 5.0"
  - dependency-name: webpack-cli
    versions:
    - ">= 4.0"
  - dependency-name: webpack-dev-server
    versions:
    - ">= 4.0"
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: ts-loader
    versions:
    - 9.0.0
    - 9.1.0
  - dependency-name: "@types/webpack"
    versions:
    - 5.0.0
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.0
  - dependency-name: "@commitlint/prompt-cli"
    versions:
    - 12.0.0
  - dependency-name: eslint-config-airbnb-typescript
    versions:
    - 12.0.1
    - 12.2.0
    - 12.3.0
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
